#!/bin/bash
rm -r /tmp/my_first_directory
[master 10ab5b8] Delete the directory my_first_directory that is in the /tmp directory
 1 file changed, 2 insertions(+)
 create mode 100755 0x00-shell_basics/9-firstdirdeletion
